[package]
name = "jrnl-back"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
axum = { version = "0.7.7", features = ["json"] }
dotenvy = "0.15.7"
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "tls-native-tls", "postgres", "migrate", "chrono", "uuid" ] }
tokio = { version = "1.41.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
chrono = { version = "0.4.38" , features = ["serde"]}
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
reqwest = { version = "0.12.8", features = ["json"] }
uuid = { version = "1.11.0" , features = ["v4", "serde", "fast-rng", "macro-diagnostics"]}
chrono-tz = "0.10.0"

[lints.clippy]
all = "warn"
correctness = "deny"
suspicious = "deny"
complexity = "deny"
perf = "deny"
style = "deny"
pedantic = "warn"
nursery = "warn"

[lints.rust]
warnings = "warn"
future-incompatible = "warn"
nonstandard-style = "warn"