services:
  jrnl-front:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - NUXT_PUBLIC_API_BASE=https://my.jrnl.fm
      - NUXT_PUBLIC_APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      - NUXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NODE_ENV=production
    build:
      context: ./jrnl-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  jrnl-back:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=https://my.jrnl.fm
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY}
    build:
      context: ./jrnl-back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5432:5432"
    volumes:
      - jrnl-back-cache:/app/cache

volumes:
  jrnl-back-cache:
